title: No title
author: ME
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  When can I get home and have a burger?
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
